name: flutter_resources2
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  asuka: '>=2.2.1'
  bubble: '>=1.2.1'
  core_resources:
    git:
      path: core_resources
      url: https://github.com/icarohs7/flutter-resources
  diacritic: '>=0.1.5'
  equatable: '>=2.0.5'
  extended_image: '>=8.2.1'
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_image_compress:
    git:
      path: packages/flutter_image_compress
      ref: c2db80264a15162f05ca610570e8bc0cef9d4377
      url: https://github.com/alainjr10/flutter_image_compress
  flutter_secure_storage: '>=9.2.4'
  freezed_annotation: '>=2.4.4'
  get_it: '>=7.2.0'
  hive_ce_flutter: '>=2.3.3'
  html_unescape: '>=2.0.0'
  image: '>=4.2.0'
  masked_text_resources:
    git:
      path: masked_text_resources
      url: https://github.com/icarohs7/flutter-resources
  omni_datetime_picker: '>=2.3.1'
  reactor_fp_resources:
    git:
      path: reactor_fp_resources
      url: https://github.com/icarohs7/flutter-resources
  search_resources:
    git:
      path: search_resources
      url: https://github.com/icarohs7/flutter-resources
  share_plus: '>=10.1.4'
  skeletonizer: '>=2.0.0'
  store_redirect:
    git:
      ref: ad9c6f7f1729bfa273bf3fba329d8aa5ec42041e
      url: https://github.com/Eufranio/store_redirect
  stream_resources:
    git:
      path: stream_resources
      url: https://github.com/icarohs7/flutter-resources
  super_sliver_list: '>=0.4.1'
  url_launcher: '>=6.3.0'
  value_notifier_resources:
    git:
      path: value_notifier_resources
      url: https://github.com/icarohs7/flutter-resources
dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: any
  json_serializable: any
  mockito: ^5.6.1
  mocktail: ^1.0.4
flutter:
  uses-material-design: true
scripts:
  build_runner_clean: flutter pub run build_runner clean
  build_runner: flutter pub run build_runner build
  brc: rps build_runner_clean
  br: rps build_runner
  brcb:
    $script: rps brc
    $after: rps br -d
  preview: flutter widget-preview start